<?php

/**
 * Implementation of hook_menu().
 */
function shipwire_perm() {
  return array('manage shipwire fulfillment', 'manually reprocess shipwire orders');
}

function shipwire_menu() {
  $items = array();

  $items['admin/store/shipwire'] = array(
    'title' => t('Shipwire'),
    'description' => t('Manage fulfillment services through Shipwire.'),
    'page callback' => 'shipwire_landing_page',
    'access arguments' => array('manage shipwire fulfillment'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/store/shipwire/settings'] = array(
    'title' => t('Shipwire Settings'),
    'description' => t('Shipwire fulfillment settings.'),
    'page callback' => 'shipwire_settings_page',
    'access arguments' => array('manage shipwire fulfillment'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function shipwire_landing_page() {
  return t('Test');
}

/**
 * Implements a static menu callback to return the form.
 */
function shipwire_settings_page() {
  return drupal_get_form('shipwire_settings_form');
}

/**
 * Implemenation of hook_form().
 */
function shipwire_settings_form(&$node, $form_state) {
  $form['shipwire']['email']  = array(
    '#title' => t('Email'),
    '#description' => t('The email address associated with your Shipwire account.'),
    '#type' => 'textfield',
    '#size' => 30,
    '#default_value' => variable_get('shipwire_email', 'example@example.com'),
    '#maxlength' => 64,
  );

  $form['shipwire']['password'] = array(
    '#title' => t('Password'),
    '#description' => t('The password for the Shipwire account.'),
    '#type' => 'password',
    '#value' => variable_get('shipwire_password', 'test'),
    '#size' => 20,
  );

  $form['shipwire']['environment'] = array(
    '#title' => t('Environment'),
    '#description' => t('This field is set via a variable set. It is not set via the UI.'),
    '#type' => 'select',
    '#value' => variable_get('shipwire_environment', 'test'),
    '#options' => array('test', 'production'),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Implementation of hook_submit().
 */
function shipwire_settings_form_submit($form, $form_state) {
  variable_set('shipwire_email', $form['shipwire']['email']['#value']);
  variable_set('shipwire_password', $form['shipwire']['password']['#value']);

  if ($form['shipwire']['environment']['#value'] == 1) {
    variable_set('shipwire_environment', 1);
  }
  else {
    variable_set('shipwire_environment', 0);
  }
}
